### ISSUE TITLE
it is recommended to switch debug mode on the quits

### ISSUE THREAD

**Issue by Devsignerz** [jakeajames/Prometheus#4]
so as i said above, it does that and i tried enabling it in the project's main.storyboard but im not sure if it's gonna also change the code and actually enable it or not. if not, where can i change it?

**Comment by jakeajames** [comment]
You enable it on the app, that's not required, just a recommendation

**Comment by jakeajames** [comment]
If it quits, then make sure you run install.sh and it succeeds

**Comment by Devsignerz** [comment]
oooh i thought it's the thing that runs the actual futurerestore. didnt know it installs the depencies. thanks man!
